### ISSUE TITLE
Determine game loop

### ISSUE THREAD

**Issue by araml** [Optativa/Optativa#4]

**Comment by dysoco** [comment]
Que me asignas si no se ni de que es el juego

**Comment by Saeuissimus** [comment]
2D Coop Survival.
Each player controls one character.
Characters have abilities.

**Comment by araml** [comment]
- La idea es splitear el concepto de metroidvania en varias personas
- Las habilidades de un metroidvania comun se separan en varias clases. 
- Cada persona tiene que tomar el rol de una o varias clases dependiendo de cuantas hay (Un jugador solo tomaria el rol de todas las clases, como un metroidvania comun)
- Los upgrades se obtienen como en un metroidvania comun.
- En un periodo contemporaneo las clases tendrían una pinta como por ej
- Demolisher (Rompe puertas/piedras/paredes de distinto tamaño)
- Hacker (Hackea locks, camaras, torretas de defensa, etc)
- Scout (Puede saltar mas alto, meterse por ductos)
- Soldier (Tiene mas poder de fuego, matar ciertos bichos molestos que otros no pueden)
